// Code generated by github.com/vektah/dataloaden, DO NOT EDIT.

package articletag

import (
	"sync"
	"time"
)

// LoaderByArticleIDConfig captures the config to create a new LoaderByArticleID
type LoaderByArticleIDConfig struct {
	// Fetch is a method that provides the data for the loader
	Fetch func(keys []LoaderByArticleIDKey) ([][]ArticleTag, []error)

	// Wait is how long wait before sending a batch
	Wait time.Duration

	// MaxBatch will limit the maximum number of keys to send in one batch, 0 = not limit
	MaxBatch int
}

// NewLoaderByArticleID creates a new LoaderByArticleID given a fetch, wait, and maxBatch
func NewLoaderByArticleID(config LoaderByArticleIDConfig) *LoaderByArticleID {
	return &LoaderByArticleID{
		fetch:    config.Fetch,
		wait:     config.Wait,
		maxBatch: config.MaxBatch,
	}
}

// LoaderByArticleID batches and caches requests
type LoaderByArticleID struct {
	// this method provides the data for the loader
	fetch func(keys []LoaderByArticleIDKey) ([][]ArticleTag, []error)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
	cache map[LoaderByArticleIDKey][]ArticleTag

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *loaderByArticleIDBatch

	// mutex to prevent races
	mu sync.Mutex
}

type loaderByArticleIDBatch struct {
	keys    []LoaderByArticleIDKey
	data    [][]ArticleTag
	error   []error
	closing bool
	done    chan struct{}
}

// Load a ArticleTag by key, batching and caching will be applied automatically
func (l *LoaderByArticleID) Load(key LoaderByArticleIDKey) ([]ArticleTag, error) {
	return l.LoadThunk(key)()
}

// LoadThunk returns a function that when called will block waiting for a ArticleTag.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *LoaderByArticleID) LoadThunk(key LoaderByArticleIDKey) func() ([]ArticleTag, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() ([]ArticleTag, error) {
			return it, nil
		}
	}
	if l.batch == nil {
		l.batch = &loaderByArticleIDBatch{done: make(chan struct{})}
	}
	batch := l.batch
	pos := batch.keyIndex(l, key)
	l.mu.Unlock()

	return func() ([]ArticleTag, error) {
		<-batch.done

		var data []ArticleTag
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many keys at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
func (l *LoaderByArticleID) LoadAll(keys []LoaderByArticleIDKey) ([][]ArticleTag, []error) {
	results := make([]func() ([]ArticleTag, error), len(keys))

	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}

	articleTags := make([][]ArticleTag, len(keys))
	errors := make([]error, len(keys))
	for i, thunk := range results {
		articleTags[i], errors[i] = thunk()
	}
	return articleTags, errors
}

// LoadAllThunk returns a function that when called will block waiting for a ArticleTags.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *LoaderByArticleID) LoadAllThunk(keys []LoaderByArticleIDKey) func() ([][]ArticleTag, []error) {
	results := make([]func() ([]ArticleTag, error), len(keys))
	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}
	return func() ([][]ArticleTag, []error) {
		articleTags := make([][]ArticleTag, len(keys))
		errors := make([]error, len(keys))
		for i, thunk := range results {
			articleTags[i], errors[i] = thunk()
		}
		return articleTags, errors
	}
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
func (l *LoaderByArticleID) Prime(key LoaderByArticleIDKey, value []ArticleTag) bool {
	l.mu.Lock()
	var found bool
	if _, found = l.cache[key]; !found {
		// make a copy when writing to the cache, its easy to pass a pointer in from a loop var
		// and end up with the whole cache pointing to the same value.
		cpy := make([]ArticleTag, len(value))
		copy(cpy, value)
		l.unsafeSet(key, cpy)
	}
	l.mu.Unlock()
	return !found
}

// Clear the value at key from the cache, if it exists
func (l *LoaderByArticleID) Clear(key LoaderByArticleIDKey) {
	l.mu.Lock()
	delete(l.cache, key)
	l.mu.Unlock()
}

func (l *LoaderByArticleID) unsafeSet(key LoaderByArticleIDKey, value []ArticleTag) {
	if l.cache == nil {
		l.cache = map[LoaderByArticleIDKey][]ArticleTag{}
	}
	l.cache[key] = value
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *loaderByArticleIDBatch) keyIndex(l *LoaderByArticleID, key LoaderByArticleIDKey) int {
	for i, existingKey := range b.keys {
		if key == existingKey {
			return i
		}
	}

	pos := len(b.keys)
	b.keys = append(b.keys, key)
	if pos == 0 {
		go b.startTimer(l)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l)
		}
	}

	return pos
}

func (b *loaderByArticleIDBatch) startTimer(l *LoaderByArticleID) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l)
}

func (b *loaderByArticleIDBatch) end(l *LoaderByArticleID) {
	b.data, b.error = l.fetch(b.keys)
	close(b.done)
}
